import ".././index.css";
import { useState } from "react";

const Actionable = () => {
  const [Prompt, SetPrompt]: any = useState(
    "Consider Implementing Crop Rotation in your farm"
  );
  return (
    <div className="flex flex-col bg-slate-300 rounded-md p-3 w-128 h-32 drop-shadow-md text-wrap">
      <div className="<<Title>>">
        <h1 className="text-xl">Recommended Action</h1>
      </div>
      <div className="<<Prompt>> text-size-md text-wrap">
        <p className="text-md text-wrap">{Prompt}</p>
      </div>
      <div>
        <p className="text-sm text-slate-700">
          this response was generated by ai
        </p>
      </div>
    </div>
  );
};

export default Actionable;
